### ISSUE TITLE
error using computeInfoVal2IFC()?

### ISSUE THREAD

**Issue by FDamon** [rdotsch/rcicr#102]
I may be wrong but in `computeInfoVal2IFC()` the line `cinorm<-norm(matrix(ci[["ci"]]),"f")` uses the variable "ci" that as been loaded in rdata, which in fact corresponds to the computed reference distribution, and not the ci previously computed in `generateCI()`.  This is because when the reference distribution is computed, the rdata is saved with the variable named "ci" corresponding to the reference distribution values, and this variable unfortunately replaces the one we feed into the function `computeInfoVal2IFC()`, e.g. `infoVal <- computeInfoVal2IFC(ci, rdata)`. 
For the script to work I had to change the name of the variable I feed to `computeInfoVal2IFC()`: `infoVal <- computeInfoVal2IFC(Fixci, rdata)`,  and the line 60 of `computeInfoVal2IFC` in ` cinorm<-norm(matrix(Fixci[["ci"]]),"f")`. 
Am I doing something wrong here?
Maybe this could be corrected just by changing the name of the variable "ci" in `generateReferenceDistribution2IFC()`?

**Comment by rdotsch** [comment]
Hi FDamon,

Thank you for your comment. I  think you are right. 'ci' actually does not need to be written to the reference distributions rdata file. It's the last random ci that was generated. 

I propose we change two things: 
1. add `rm(ci)` to `generateReferenceDistribution2IFC()` before writing to the rdata file.
2. name the ci paramater in `computeInfoVal2IFC` differently in both the function definition and the body. For instance to `target_ci`. 

If you have time, feel free to fork the repo, adapt the code, and send a pull request that I can review and then merge if ok. 

Best,

Ron

**Comment by FDamon** [comment]
Hi Ron,

OK, I will change this. 
Thanks for the rcicr package, this is great!

Cheers,
Fabrice
