### ISSUE TITLE
negative infoVal

### ISSUE THREAD

**Issue by teresa-canasbajo** [rdotsch/rcicr#108]
Hi there,

 I have use your package to extract the infoVal for each subject and one subject seems to have negative infoVals most of the time. Would you give me a hint as to how to interpret significant (out of the reference norm distribution) negative values?

Thanks!

**Comment by rdotsch** [comment]
This may happen when the observed vector length of the CI is near 0 and lower than the central tendency of the reference distribution. This is the case for instance when the noise patterns of the stimuli a participant selects almost completely cancel each other out. It can still be interpreted as not significantly different from random responding.
