### ISSUE TITLE
reference_norms are the same for all .rdata files 

### ISSUE THREAD

**Issue by aidangauper** [rdotsch/rcicr#109]
After computing infoval for multiple CIs, each reference_norms is identical. Each CI was created from a different base image and has a unique corresponding rdata file. To my understanding, each reference_norms should be randomly generated. Calling both computeInfoVal2IFC and generateReferenceDistribution2IFC creates identical reference distributions.

**Comment by rdotsch** [comment]
The reference distributions are computed using the same seed for the random number generator as specified in the .Rdata file that was used when generating the stimuli. This was intended for reproducibility. However, it may be better to decouple the seed for stimuli production from the seed for generating the reference distribution given your specific use case. I’ll adjust this in my next commit.

**Comment by aidangauper** [comment]
Thanks! Another question: don't reference distributions depend on the particular parameters of the stimuli contained in the rdata file? Shouldn't different rdata files, even with the same seed and stimulus length, produce different reference distributions since the stimuli are different? Our reference distributions are the same despite being generated from unique rdata files with different associated base images. 

From generateReferenceDistribution2IFC:

![image](https://user-images.githubusercontent.com/56613443/92643050-ff919000-f295-11ea-9945-34ee1bfbc299.png)

**Comment by rdotsch** [comment]
No, reference distributions ignore the base image and only look at the noise patterns. These are the same when you have the same number of stimuli and the same seed and so you will have the same reference distributions.

**Comment by aidangauper** [comment]
That helps a lot, thanks!
