### ISSUE TITLE
batchGenerateCI2IFC not generating CIs

### ISSUE THREAD

**Issue by ryanetracy** [rdotsch/rcicr#110]
I just ran a reverse correlation pilot study. I had no issue creating the aggregate CI across all participants, but had an issue using batchGenerateCI2IFC. Specifically, every time I run the function I get the following error:

Error in aggregate.data.frame(responses, by = list(stimuli = stimuli),  : 
  arguments must have same length

I've double checked everything I can think of, including the number of trials per participant (same), number of times each stimulus was seen (same), and can't think of what else to check. I can provide the code if needed.

**Comment by rdotsch** [comment]
Take a look at the number of elements in responses and the number of elements in stimuli. Are they the same?

**Comment by ryanetracy** [comment]
Number of elements in each is the same. 200 trials per participant, 9 total participants, no excluded trials for any individual.

**Comment by rdotsch** [comment]
Please paste your code so we can see what may be going wrong.

**Comment by ryanetracy** [comment]
Here's the code. Data was collected via a psychopy study hosted on pavlovia, if that clarifies anything.

library(tidyverse)
library(rcicr)
library(stringr)

#download pilot data
pilotCIs <- list.files(path = "study 1/biracial rc pilot data",
                       pattern = "*.csv",
                       full.names = T) %>%
  map_df(~read_csv(., col_types = cols(.default = "c")))

#one person entered their actual ID instead of the number given by the random generator, so replace that
pilotCIs$ID_number <- with(pilotCIs, ifelse(ID_number == '5eaacde0b5205203d43a47af', 8755, ID_number))

#get image data
pilotData <- pilotCIs[,c(20,5,14,15,16,17)]
pilotData <- na.omit(pilotData)

#add in stim number
pilotData$stimNums <- substr(pilotData$originalImg,23,25)
pilotData$stimNums <- as.numeric(pilotData$stimNums)

#recode data (1 = original chosen, -1 = inverse chosen)
pilotData$response <- with(pilotData, ifelse(origLocX == 300 & imageChoice.keys == "right", 1, 
                                         ifelse(origLocX == -300 & imageChoice.keys == "left", 1, -1)))

#set base image and image data to objects
baseimg <- 'base'

rDat <- 'stimuli/rcic_seed_1_time_May_18_2020_13_41.Rdata'
load(rDat)

pilotData$ID_number <- as.numeric(pilotData$ID_number)

#average CI (all participants)
cisPilot <- generateCI2IFC(stimuli = pilotData$stimNums,
                           responses = pilotData$response,
                           baseimage = baseimg,
                           rdata = rDat)

#batch CI (each participant)
partCIs <- batchGenerateCI2IFC(data = pilotData,
                               by = 'ID_number',
                               stimuli = 'stimNums',
                               responses = 'response',
                               baseimage = baseimg,
                               rdata = rDat)
