### ISSUE TITLE
large negative infovals

### ISSUE THREAD

**Issue by teresa-canasbajo** [rdotsch/rcicr#114]
Hello,

 I am getting largely negative infovalues (-8). In a previous github issue it was explained to me how some negative values are just null values, but I thought that the infoval could not get that negative (from Brinkman et al., 2018 Fig. 3). Plus, the generated CI (attached) is clearly not just noise, so it can't be just null. Any idea what may be happening?

![image](https://user-images.githubusercontent.com/25251231/94227215-a426eb00-feae-11ea-81a7-78aafe2cedd3.png)
Generated from 2000 trials.

Thank you so much!

**Comment by rdotsch** [comment]
This is interesting. I am not sure what is going on. Are you sure the number of trials used for the simulation is the same as for the task that generated the CI?
