### ISSUE TITLE
gamma correction of trial stimulus noise

### ISSUE THREAD

**Issue by teresa-canasbajo** [rdotsch/rcicr#115]
I'm trying to do some simulations of the influence of gamma correction in the noise stimuli in the resulting CI using this package. I know the noise stimuli for each trial is stored in the params variable and then used in generateCINoise but, I'm not sure how you would apply gamma correction to the 4092 values that describe the noise of each stimuli. It's first time I see the noise computed in this way. Do you have any ideas? 

Thanks!

**Comment by rdotsch** [comment]
I think you would rescale the output of generateCInoise, which are pixel values, not the parameters that go into that function.
