### ISSUE TITLE
Remove aspace dependency

### ISSUE THREAD

**Issue by rdotsch** [rdotsch/rcicr#116]
Lately when you try to install the rcicr package, you get the following error message:

```
ERROR: dependency ‘aspace’ is not available for package ‘rcicr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rcicr’
Warning messages:
1: package ‘aspace’ is not available for this version of R
```

Current workaround:

```
install.packages(c("devtools", "Hmisc", splancs"))
require(devtools)
> install_version("aspace", version = "3.2", repos = "http://cran.us.r-project.org")
```

We need to remove dependency on aspace.

**Comment by liuzhijun5315** [comment]
when i fllowed:
install.packages(c("devtools", "Hmisc", splancs"));require(devtools)
install_version("aspace", version = "3.2", repos = "http://cran.us.r-project.org")
library(usethis);library(devtools)
Install rcicr package (development version)


Warning: replacing previous import 'scales::viridis_pal' by 'viridis::viridis_pal' when loading 'rcicr'
object ‘as.im’ is not exported by 'namespace:spatstat'

as.im?????

**Comment by jwylie21** [comment]
I am also having this issue. Following the workaround I get this error message:

Warning: replacing previous import 'scales::viridis_pal' by 'viridis::viridis_pal' when loading 'rcicr'
object ‘as.im’ is not exported by 'namespace:spatstat'

**Comment by rdotsch** [comment]
aspace dependency removed, workaround no longer needed. The new warning is referenced in #117
