### ISSUE TITLE
replacing previous import 'scales::viridis_pal' by 'viridis::viridis_pal' ......object 'as.im' is not exported

### ISSUE THREAD

**Issue by liuzhijun5315** [rdotsch/rcicr#117]
install.packages(c("devtools", "Hmisc", "splancs"));
require(devtools)
install_version("aspace", version = "3.2", repos = "http://cran.us.r-project.org")
Install rcicr package (development version)

Warning: replacing previous import 'scales::viridis_pal' by 'viridis::viridis_pal' when loading 'rcicr'
ERROR:  object ‘as.im’ is not exported by 'namespace:spatstat'

**Comment by rdotsch** [comment]
Thank you for flagging. Looks like I need to update the package imports like described here: https://github.com/wpeterman/ResistanceGA/issues/15

When I have time, I’ll update the package.

**Comment by liuzhijun5315** [comment]
thanks. i try it by this:
install.packages('https://cran.r-project.org/src/contrib/Archive/spatstat/spatstat_1.64-1.tar.gz', repos=NULL,type="source", INSTALL_opts = "--no-lock")

it seems ok.

**Comment by rdotsch** [comment]
This is now fixed in the latest commit to the development branch
