### ISSUE TITLE
couldn't install the pacakge

### ISSUE THREAD

**Issue by baixx062** [rdotsch/rcicr#120]
Hi there, I tried installing it with the command devtools::install_github('rdotsch/rcicr'), but then it gave the following error code, and doesn't allow me to install it properly. Help?

> 
> 
> devtools::install_github('rdotsch/rcicr')
Downloading GitHub repo rdotsch/rcicr@HEAD
Installing 2 packages: terra, raster
Installing packages into ‘/Users/HB/Library/R/4.0/library’
(as ‘lib’ is unspecified)

  There are binary versions available but the source versions are later:
       binary source needs_compilation
terra  1.5-21 1.6-17              TRUE
raster 3.5-15  3.6-3              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) Yes
installing the source packages ‘terra’, ‘raster’

trying URL 'https://cran.rstudio.com/src/contrib/terra_1.6-17.tar.gz'
Content type 'application/x-gzip' length 698382 bytes (682 KB)
==================================================
downloaded 682 KB

trying URL 'https://cran.rstudio.com/src/contrib/raster_3.6-3.tar.gz'
Content type 'application/x-gzip' length 579228 bytes (565 KB)
==================================================
downloaded 565 KB

* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang
configure: CXX: clang++ -mmacosx-version-min=10.13 -std=gnu++11
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/Users/HB/Library/R/4.0/library/terra’
ERROR: dependency ‘terra’ is not available for package ‘raster’
* removing ‘/Users/HB/Library/R/4.0/library/raster’

The downloaded source packages are in
	‘/private/var/folders/1l/xn8kvlz17l7093wyjt4ndn440000gs/T/RtmpgibtVb/downloaded_packages’
✓  checking for file ‘/private/var/folders/1l/xn8kvlz17l7093wyjt4ndn440000gs/T/RtmpgibtVb/remotes9699110bb987/rdotsch-rcicr-02c33b9/DESCRIPTION’ ...
─  preparing ‘rcicr’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rcicr_1.0.0.tar.gz’
   
Installing package into ‘/Users/HB/Library/R/4.0/library’
(as ‘lib’ is unspecified)
ERROR: dependency ‘raster’ is not available for package ‘rcicr’
* removing ‘/Users/HB/Library/R/4.0/library/rcicr’
Warning messages:
1: In i.p(...) : installation of package ‘terra’ had non-zero exit status
2: In i.p(...) : installation of package ‘raster’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/var/folders/1l/xn8kvlz17l7093wyjt4ndn440000gs/T//RtmpgibtVb/file969918c156cf/rcicr_1.0.0.tar.gz’ had non-zero exit status

**Comment by rdotsch** [comment]
Looks like this is an issue of the terra package which is an indirect dependency. You may try to install a previous version of that package prior to installing rcicr. Hopefully this issue will get fixed by the terra developers soon.

**Comment by rdotsch** [comment]
I can't replicate this error today, so I am assuming that the terra package has been updated. Closing this issue.

**Comment by marek1n** [comment]
as the error states, terra requires a gdal installation e.g. simply `brew install gdal` solved this for me
