### ISSUE TITLE
ERROR: dependency 'spatstat.core' is not available for package 'rcicr'

### ISSUE THREAD

**Issue by jrk1** [rdotsch/rcicr#121]
Hi Ron,

hope you are good and had a nice start into the new year. I am struggling installing RCICR at the moment with the newest R build (4.2). I get the error "ERROR: dependency 'spatstat.core' is not available for package 'rcicr'

I have tried a few older R versions now but don't seem to get it to work. Any help would be appreciated.

Best,
Jonas

**Comment by rdotsch** [comment]
Looks like `spatstat.core` is no longer maintained or on CRAN: https://cran.r-project.org/web/packages/spatstat.core/index.html. The package is replaced by other packages (https://github.com/spatstat/spatstat.core). I will need to update rcicr to use the new packages. Stay tuned.

**Comment by rdotsch** [comment]
I updated it, `devtools::install_github('rdotsch/rcicr')` should now install without problems on your R build.

**Comment by jrk1** [comment]
Thanks a lot, Ron! Works fine for me so far!
