### ISSUE TITLE
Errors prior to install dev version

### ISSUE THREAD

**Issue by irenetorrubia** [rdotsch/rcicr#48]
Before I could install the dev version of rcicr, I had to manually install the following packages: 

- DBI
- assertthat
- tibble
- munsell
- plyr
- ggplot2
- gridExtra
- sp

Otherwise I got an error message like: 

* installing *source* package 'rcicr' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'sp'
ERROR: lazy loading failed for package 'rcicr'
* removing 'C:/Users/xx/Documents/R/win-library/3.3/rcicr'

**Comment by rdotsch** [comment]
Thanks, we will look into this.

**Comment by olivethree** [comment]
Had the same problem but while loading the rcicr library after (apparently) successfully installing rcicr 0.4.0. The missing packages were the same as those reported above. Also, this was done in a totally new and clean R project (with default R packages only). 

Here's the log (only removed the package installation lines in-between library loadings):

* installing *source* package 'rcicr' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (rcicr)

> library(rcicr)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘DBI’
Error: package or namespace load failed for ‘rcicr’

> library(rcicr)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘assertthat’
Error: package or namespace load failed for ‘rcicr’


> library(rcicr)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Rcpp’
Error: package or namespace load failed for ‘rcicr’

> library(rcicr)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘magrittr’
Error: package or namespace load failed for ‘rcicr’

> library(rcicr)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘tibble’
Error: package or namespace load failed for ‘rcicr’

> library(rcicr)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘munsell’
Error: package or namespace load failed for ‘rcicr’

> library(rcicr)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘plyr’
Error: package or namespace load failed for ‘rcicr’

> library(rcicr)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘ggplot2’
Error: package or namespace load failed for ‘rcicr’

> library(rcicr)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘gridExtra’
Error: package or namespace load failed for ‘rcicr’

> library(rcicr)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘sp’
Error: package or namespace load failed for ‘rcicr’

**Comment by rdotsch** [comment]
This should be fixed now. If you get any chance to test this again, please let me know if everything works as it should now.
