### ISSUE TITLE
Error with the Parallel Socket Cluster

### ISSUE THREAD

**Issue by irenetorrubia** [rdotsch/rcicr#49]
If I run 

```
generateStimuli2IFC(base_face_files = "RefImage.jpg", n_trials = 1000, img_size = 512,
                    stimulus_path = "./stimuli", label = "rcic", use_same_parameters = TRUE,
                    seed = 1, maximize_baseimage_contrast = F, noise_type = "sinusoid",
                    nscales = 5, sigma = 25,  ncores = detectCores(), returnAsList = TRUE)
```

It returns the error message 

> Error in makePSOCKcluster(spec, ...) : 
>   could not find function "detectCores"

When I tried to run it again (I removed  ncores = detectCores(), although I assumed that nothing would happen), I get the following error message:

>  Error in { : 
>   task 1 failed - "attempt to select less than one element in get1index"

**Comment by rdotsch** [comment]
Thanks Irene. I'll fix this in the next commit. In the meantime, your hunch to just drop `ncores = detectCores()` is the right one. The error you get is because the base_face_files argument should be a named list instead of just an image. For instance `base_face_files = list("refimage=RefImage.jpg").  The error feedback you receive is very cryptic right now, I'll change that in a next commit as well.

**Comment by irenetorrubia** [comment]
I added `base_face_files = list("refimage=RefImage.jpg") and dropped nscores but I still get the error message

> Error in { : 
>   task 1 failed - "attempt to select less than one element in get1index"

**Comment by rdotsch** [comment]
Sorry, I made a typo, it has to be:

`base_face_files = list(refimage="RefImage.jpg")`

**Comment by irenetorrubia** [comment]
I missed the typo. It works, thanks!!

**Comment by olivethree** [comment]
Also got the same error (**"Error in makePSOCKcluster(spec, ...) : could not find function "detectCores"**) while using the generateCI function. But the error only occurred when I changed the argument **zmapmethod** to "t.test", or provided input for the **participants** argument.   

The error was apparently overrode when the number of cores was manually specified (= 2) with the **zmapmethod** set to "t.test". But after a while running this new error popped up:

 **Error in dim(noiseimages) <- c(img_size, img_size, n_observations) : 
  dims [product 19660800] do not match the length of object [300]**

Note: the data I fed into it works fine with the public package.

**Comment by rdotsch** [comment]
The problem with detectCores should be fixed now. Let me know if it works, when you reinstall the newest dev version with `install_github`. @olivethree, would you mind making a new issue for the `dim(noiseimages)` problem?

**Comment by olivethree** [comment]
Issue disappeared after updating to the newest dev version. Way faster now, regardless of whether the zmapmethod is set to "quick" or "t.test". The dim(noiseimages) error also disappeared.
