### ISSUE TITLE
Images should not be saved as JPEG

### ISSUE THREAD

**Issue by PatrickLaflamme** [rdotsch/rcicr#55]
I noticed that your package exports all experiment images as JPEG. The problem with this is that JPEG can alter the intensity and location of pixels in an image due to the compression method that it uses. If you were presenting solely noise that was generated by your package, it would not be a problem. Your noise generation actually mirrors the way that JPEG compression works, so converting your noise to JPEG would be lossless - I assume this was intentional. However, it is important to note that the nature of the base image may be altered slightly during JPEG compression. I would strongly suggesting creating PNG files instead. This should be relatively easy to implement since base R can write PNG images and the package 'imager' can be used to convert arrays into bitmap image format. I'd be happy to implement it myself if you like.

here is a reference for the effect of JPEG compression on image quality. It's specifically mentioned in section 6.8:
[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4210356/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4210356/)

**Comment by rdotsch** [comment]
Thanks for the comment and your offer to implement. You are right and we have already fixed this in the development branch of rcicr.

**Comment by aucuparia** [comment]
Fixed already indeed, but thank you for taking the effort to report it!
