### ISSUE TITLE
More informative error message needed for incorrect base image size

### ISSUE THREAD

**Issue by rdotsch** [rdotsch/rcicr#58]
This fails: `generateStimuli2IFC(list('mnes'='MNES.JPG'), n_trials = 10)`. 

This is the output: 

```starting worker pid=2702 on localhost:11803 at 11:44:26.970
starting worker pid=2710 on localhost:11803 at 11:44:27.173
starting worker pid=2718 on localhost:11803 at 11:44:27.387
starting worker pid=2726 on localhost:11803 at 11:44:27.597
Loading required package: rcicr
Loading required package: rcicr
Loading required package: rcicr
Loading required package: rcicr
loaded rcicr and set parent environment
loaded rcicr and set parent environment
loaded rcicr and set parent environment
loaded rcicr and set parent environment
Error in { : task 1 failed - "non-conformable arrays"
```

We should fix this ASAP.

**Comment by rdotsch** [comment]
Solved it.

**Comment by rdotsch** [comment]
The error was that the base image size was not 512x512. We need a more informative error message.

**Comment by dongwonoh** [comment]
(Perhaps) related to this issue, generateStimuli2IFC outputs a similar error message when the size of the baseline photo is not the same with _img_size_. It would be great for users if the error message was more informative!

> Error in stimulus + base_faces[[base_face]] : non-conformable arrays
