### ISSUE TITLE
computeInfoVal2IFC() Error reading .jpg base image

### ISSUE THREAD

**Issue by nmmichalak** [rdotsch/rcicr#98]
# R code
computeInfoVal2IFC(ci = my_ci_data, rdata = my_rdata)

# message suggesting package is loaded and so is function
Re-generating stimuli based on rdata file, please wait...

# Error message
Error in jpeg::readJPEG(filename) : unable to open MNES.jpg

**Comment by qubitter** [comment]
As far as I can tell, (assuming you somehow still haven't solved this), you need to put MNES.jpg (your base image) in the same folder as your code. Otherwise, please mark this as closed.
