### ISSUE TITLE
ComputeInfoVal2IFC error: "Error in ci$ci : $ operator is invalid for atomic vectors"

### ISSUE THREAD

**Issue by pzpsych** [rdotsch/rcicr#99]
I'm using the code below to try to get InfoVal values:
baseimage <- 'female'
rdata <- 'rcic_seed_1_time_Sep_12_2018_15_46.rdata'
ci <- generateCI(p11$trial, p11$response, baseimage, rdata)
infoval <- computeInfoVal2IFC(ci, rdata)

I keep getting the following error when running the computeInfoVal2IFC line (the rest works fine):
Error in ci$ci : $ operator is invalid for atomic vectors

This occurs almost immediately if I use an rdata file that I've added the reference distribution to with generateReferenceDistribution2IFC, or if I haven't, it occurs after it creates the reference distribution.

I'm new to coding and to GitHub, so I apologize if this is a dumb question or inappropriate to post as an issue like this. I've been reading about InfoVal for years now and would really like to get it to work. =)

**Comment by qubitter** [comment]
This is also an issue that I've been experiencing, except for me, it occurs after the infoVal progress bar fills to 100%. I've converted all usages of the $ operator to [[]] in my code, so it must be with rcicr. Any help?
